@base_url = http://localhost:3000

## register member
POST {{base_url}}/register/individual HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "first_name": "polawat",
  "last_name": "phetra",
  "email": "pphetra@gmail.com",
  "address_line_1": "141/3",
  "address_line_2": "bangkok",
  "address_postal_code": "10900"
}

## get member
